//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_pred
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract_pred()
        {
            this.Employee_strah_sluch = new HashSet<Employee_strah_sluch>();
        }
    
        public int id_contract { get; set; }
        public Nullable<System.DateTime> date_conclusion { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> id_agent { get; set; }
        public Nullable<int> id_predriyat { get; set; }
        public Nullable<decimal> sum_pay { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Predpriyat Predpriyat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_strah_sluch> Employee_strah_sluch { get; set; }
    }
}
