//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiz_lico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fiz_lico()
        {
            this.Employee_strah_sluch = new HashSet<Employee_strah_sluch>();
        }
    
        public int id_fiz_lica { get; set; }
        public string fio { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public Nullable<int> id_risk_kategory { get; set; }
        public Nullable<int> id_predpriyat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_strah_sluch> Employee_strah_sluch { get; set; }
        public virtual Risk_Kategory Risk_Kategory { get; set; }
        public virtual Predpriyat Predpriyat { get; set; }
    }
}
