//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int id { get; set; }
        public Nullable<int> idSection { get; set; }
        public Nullable<int> childAge { get; set; }
        public string name { get; set; }
        public Nullable<int> number { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
