//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsuranceEntities : DbContext
    {
        public InsuranceEntities()
            : base("name=InsuranceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<Contract_pred> Contract_pred { get; set; }
        public virtual DbSet<Employee_strah_sluch> Employee_strah_sluch { get; set; }
        public virtual DbSet<п> Enterprise_specialization { get; set; }
        public virtual DbSet<Fiz_lico> Fiz_lico { get; set; }
        public virtual DbSet<Predpriyat> Predpriyat { get; set; }
        public virtual DbSet<Risk_Kategory> Risk_Kategory { get; set; }
        public virtual DbSet<Type_Povred> Type_Povred { get; set; }
    }
}
