//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predpriyat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Predpriyat()
        {
            this.Contract_pred = new HashSet<Contract_pred>();
            this.Fiz_lico = new HashSet<Fiz_lico>();
        }
    
        public int id_predpriyat { get; set; }
        public string full_name { get; set; }
        public string short_name { get; set; }
        public string address { get; set; }
        public string bank { get; set; }
        public Nullable<int> id_specialization { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_pred> Contract_pred { get; set; }
        public virtual п Enterprise_specialization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fiz_lico> Fiz_lico { get; set; }
    }
}
