//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_Povred
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Type_Povred()
        {
            this.Employee_strah_sluch = new HashSet<Employee_strah_sluch>();
        }
    
        public int id_type { get; set; }
        public string name { get; set; }
        public Nullable<int> pay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_strah_sluch> Employee_strah_sluch { get; set; }
    }
}
